name = "svs-form-translate"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Used when deploy command is `npx wrangler deploy` (Workers static assets)
[assets]
directory = "./dist"
